type Friend = {
    latest_comment: string,
    latest_sent_by: number,
    unread: number,
    total: number,
    identity: null,
    user_status: number,
    user_id: number,
    name: string,
    show_last_login: number,
    emoji_status: string,
    avatar: string,
    location_code: string,
    dob: string,
    dob_privacy: number,
    age: number,
    gender: string,
    id: number,
    status: number,
    joined: number,
    created_at: string,
    updated_at: string,
    joined_at: string,
    user_photos: null,
    joined_photos: null,
    user_audio: null,
    joined_audio: null,
    plus: number,
    deactivated: number,
    by_id: number,
    openletter: null,
    fav: number,
    customdesc: null,
    allowphotos: number,
    photorequest: number,
    allowaudio: number,
    audiorequest: number,
}

type FriendsList = {
    friends: Friend[],
    hidden: [],
    requests: number,
}

type FriendComment = {
    id: number,
    post: number,
    user: number,
    user_to: number,
    user_fav: number,
    user_to_fav: number,
    sent_from: string,
    type: number,
    body: string,
    stamp: string,
    style: string,
    attachments: string,
    status: number,
    deliver_at: string,
    read_at: null,
    created_at: string,
    updated_at: string,
    name: string,
    avatar: string,
    location_code: string,
    gender: string,
    fav: number,
}

type FriendData = {
    post: {
        latest_comment: string,
        id: number,
        status: number,
        updated_at: string,
        created_at: string,
        joined_at: string,
        user: number,
        joined: number,
        fav: number,
        customdesc: null,
        user_photos: null,
        joined_photos: null,
        user_audio: null,
        joined_audio: null,
    },
    user: {
        id: number,
        name: string,
        gender: string,
        dob: string,
        dob_privacy: number,
        age: number,
        zodiac: string,
        show_last_login: number,
        avatar: string,
        emoji_status: string,
        about: null,
        location_code: string,
        last_login: string,
        user_status: number,
        status: number,
        distance: number,
        delivery_mins: number,
    },
    comments: {
        per_page: number,
        current_page: number,
        next_page_url: null,
        prev_page_url: null,
        from: number,
        to: number,
        data: FriendComment[],
    },
    incoming: [],
    now: string,
}
